### PR TITLE
Add notice about no windows support

### PR DESCRIPTION
**Pull request by jacobtomlinson**
Some users are having issues as we do not currently support Windows. Adding a notice to make it clear.

### CODE REVIEW

**Comment by jakirkham** [comment]
Thanks Jacob! LGTM 🙂

**Comment by jacobtomlinson** [comment]
Thanks @jakirkham. Can you approve the review so I can merge? Needs one approval to merge.

**Comment by jakirkham** [comment]
Approved! 😄

Though IDK if I have permissions here. @quasiben @rjzamora, would either of you be able to look? 🙂

**Comment by quasiben** [comment]
I think the approver has to be @rjzamora .  @dillon-cullinan can you add @jakirkham and myself to the list of reviewers ?

**Comment by jakirkham** [comment]
FWIW I raised an OPs issue about this 🙂

**Comment by jakirkham** [comment]
Thanks Rick! 😄

**Comment by jakirkham** [comment]
Apparently GitHub updates previous approvals to match whether you have permissions currently (even if you didn't have them at the time of approval).

**Pull request merged**
