### PR TITLE
Disabled automatic launcher entry

### LINKED ISSUE #98: Correctly categorizing the card in the Launcher
Hey, would it be possible to categorize the extension's launch card correctly so that it doesn't show up in Notebooks?
image
According to JupyterLab docs it should be possible:
- [JupyterLab docs](https://jupyterlab.readthedocs.io/en/stable/extension/extension_points.html#launcher)
- [JupyterLab API docs](https://jupyterlab.readthedocs.io/en/latest/api/interfaces/launcher.ilauncher.iitemoptions.html#category)

### PR DESCRIPTION
**Pull request by vidosits**
Fixes #98. Tested locally. @ian-r-rose 's [comment](https://github.com/rapidsai/jupyterlab-nvdashboard/issues/98#issuecomment-847925377) helped in quickly finding the problem. `jupyterlab-server-proxy` has documentation available on the automatically generated [launcher entry](https://jupyter-server-proxy.readthedocs.io/en/latest/server-process.html#launcher-entry).

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by ajschmidt8** [comment]
ok to test

**Review by jacobtomlinson — APPROVED** [review]
Fantastic thanks for getting this in so quickly @vidosits. And thanks @ian-r-rose for the assist!

**Comment by vidosits** [comment]
No problem, always happy to contribute to a great project!

**Pull request merged**
