### PR TITLE
Remove handlers.py

### PR DESCRIPTION
**Pull request by cmd-ntrf**
jupyterlab-nvdashboard does not setup jupyter server handlers. `setup_handlers` is never called and RouteHandler never used.

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

Admins can comment `ok to test` to allow this one PR to run or `add to allowlist` to allow all future PRs from the same author to run.

**Comment by jacobtomlinson** [comment]
ok to test

**Comment by ajschmidt8** [comment]
rerun tests

**Review by jacobtomlinson — APPROVED** [review]
Thanks @cmd-ntrf

**Pull request merged**
