### PR TITLE
Update shared-workflows version

### PR DESCRIPTION
**Pull request by AjayThorve**
Update shared-workflows version to 24.10

### CODE REVIEW

**Comment by jacobtomlinson** [comment]
Thanks @AjayThorve. @AyodeAwe there still seem to be some issues here, is this because it needs to be morged before it willt ake effect?

**Comment by AyodeAwe** [comment]
Yes this PR needs to be merged, and then an empty commit needs to pushed to https://github.com/rapidsai/jupyterlab-nvdashboard/pull/201 to re-trigger CI

**Review by jacobtomlinson — APPROVED** [review]

**Comment by jacobtomlinson** [comment]
I don't have the power to merge this with the CI failing like this. @AyodeAwe can you or @raydouglass merge this?

**Comment by jakirkham** [comment]
Let's make sure the version update script is working correctly here

https://github.com/rapidsai/jupyterlab-nvdashboard/blob/ef7c08ddf99880c090d4cc515069c56accbf39aa/ci/release/update-version.sh#L3

Maybe this needs [something similar to UCXX]( https://github.com/rapidsai/ucxx/blob/c72e739393ee5a3a639bd5b349e9653960096f8f/ci/release/update-version.sh#L73-L75 )

**Pull request merged**
