### PR TITLE
Updated the meta.yaml to use Bokeh 2.1+ and tweaked some other requirements

### PR DESCRIPTION
**Pull request by owenlamont**
Removed some unnecessary build requirements and added additional run requirements (bokeh 2.1+, jupyterlab, and nodejs).

I tested the recipe locally with conda build and it seems to be working fine when installed to a new environment.

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by owenlamont** [comment]
Thanks @jacobtomlinson - much appreciated. I wish I could've made your Dask tutorial - I'll keep an eye out for the next one.

**Comment by jacobtomlinson** [comment]
@owenlamont We are running another one in 4 hours time. If you're around I'd be happy to get you in.

**Comment by owenlamont** [comment]
> @owenlamont We are running another one in 4 hours time. If you're around I'd be happy to get you in.

@jacobtomlinson That’d be great. The eventbrite link I had showed it as “sold out” but if there’s a space in that or another I’d love to attend.

**Comment by jacobtomlinson** [comment]
@owenlamont no problem. I'll ping you on LinkedIn with the details.

**Pull request merged**
