### PR TITLE
Pass compiler environment variables to conda python build

### PR DESCRIPTION
**Pull request by Ethyling**
Pass compiler environment variables to conda python build

### CODE REVIEW

**Review by ajschmidt8 — APPROVED** [review]

**Comment by Ethyling** [comment]
rerun tests

**Comment by ajschmidt8** [comment]
needs https://github.com/rapidsai/integration/pull/273 to address some recent upstream changes in the `jupyter` conda package

**Comment by Ethyling** [comment]
rerun tests

**Comment by ajschmidt8** [comment]
rerun tests

**Pull request merged**
