### PR TITLE
Use PyNVML 12

### PR DESCRIPTION
**Pull request by jakirkham**
Bump `pynvml` from `11` to `12`. This version of `pynvml` also now depends on `nvidia-ml-py` for core functionality.

xref: https://github.com/rapidsai/jupyterlab-nvdashboard/pull/210

### CODE REVIEW

**Comment by jakirkham** [comment]
Seeing the following test failures [on CI]( https://github.com/rapidsai/jupyterlab-nvdashboard/actions/runs/12406100966/job/34636784531?pr=215#step:8:336 ):

```python
______ ERROR collecting jupyterlab_nvdashboard/tests/test_cpu_handlers.py ______
jupyterlab_nvdashboard/apps/gpu.py:15: in <module>
    nvlink_ver = pynvml.nvmlDeviceGetNvLinkVersion(gpu_handles[0], 0)
/opt/conda/envs/test/lib/python3.13/site-packages/pynvml.py:3846: in nvmlDeviceGetNvLinkVersion
    _nvmlCheckReturn(ret)
/opt/conda/envs/test/lib/python3.13/site-packages/pynvml.py:979: in _nvmlCheckReturn
    raise NVMLError(ret)
E   pynvml.NVMLError_NotSupported: Not Supported

During handling of the above exception, another exception occurred:
jupyterlab_nvdashboard/tests/test_cpu_handlers.py:5: in <module>
    from jupyterlab_nvdashboard.apps.cpu import CPUResourceWebSocketHandler
jupyterlab_nvdashboard/__init__.py:13: in <module>
    from .handlers import setup_handlers
jupyterlab_nvdashboard/handlers.py:2: in <module>
    from . import apps
jupyterlab_nvdashboard/apps/__init__.py:2: in <module>
    from . import gpu
jupyterlab_nvdashboard/apps/gpu.py:32: in <module>
    except (IndexError, pynvml.nvml.NVMLError_NotSupported):
E   AttributeError: module 'pynvml' has no attribute 'nvml'
```

```python
______ ERROR collecting jupyterlab_nvdashboard/tests/test_gpu_handlers.py ______
jupyterlab_nvdashboard/apps/gpu.py:15: in <module>
    nvlink_ver = pynvml.nvmlDeviceGetNvLinkVersion(gpu_handles[0], 0)
/opt/conda/envs/test/lib/python3.13/site-packages/pynvml.py:3846: in nvmlDeviceGetNvLinkVersion
    _nvmlCheckReturn(ret)
/opt/conda/envs/test/lib/python3.13/site-packages/pynvml.py:979: in _nvmlCheckReturn
    raise NVMLError(ret)
E   pynvml.NVMLError_NotSupported: Not Supported

During handling of the above exception, another exception occurred:
jupyterlab_nvdashboard/tests/test_gpu_handlers.py:5: in <module>
    from jupyterlab_nvdashboard.apps.gpu import (
jupyterlab_nvdashboard/__init__.py:13: in <module>
    from .handlers import setup_handlers
jupyterlab_nvdashboard/handlers.py:2: in <module>
    from . import apps
jupyterlab_nvdashboard/apps/__init__.py:2: in <module>
    from . import gpu
jupyterlab_nvdashboard/apps/gpu.py:32: in <module>
    except (IndexError, pynvml.nvml.NVMLError_NotSupported):
E   AttributeError: module 'pynvml' has no attribute 'nvml'
```

**Comment by rjzamora** [comment]
>E   AttributeError: module 'pynvml' has no attribute 'nvml'

There is no `nvml` module in nvidia-ml-py. The check should probably be `pynvml.NVMLError_NotSupported` (this should work before pynvml<12 as well)

**Comment by jakirkham** [comment]
Thanks Rick! 🙏

How do the changes above look?

**Review by jameslamb — APPROVED** [review]
Looks ok to me, based on my read of https://github.com/gpuopenanalytics/pynvml/blob/38da53a9bb031277690d6135dd3be02deb9296ac/pynvml_utils/smi.py and @rjzamora 's comments.

Would be good if @rjzamora can approve too (or at least, comment on this before the next release of `jupyterlab-nvdashboard`).

**Comment by jakirkham** [comment]
Asked Rick offline, but didn't hear back. Am guessing he is already on holiday

Given the issue above was caused by a test failure, which is resolved by the change, and Rick gave such a good description of the change required there wasn't another way to interpret it, think we have addressed his review

Also want to make sure these PRs are not lingering after the holidays. So am going to go ahead and merge

If Rick has more feedback, am happy to follow up with him

**Comment by jakirkham** [comment]
Fixed issue: https://github.com/rapidsai/jupyterlab-nvdashboard/issues/150

**Pull request merged**
