### PR TITLE
Harmonize the icon color with the standard color

### PR DESCRIPTION
**Pull request by krassowski**
Changes the `expansion-card.svg` code from `jp-icon0` class to `jp-icon3` which is more appropriate for sidebar/window icons in JupyterLab design style.

Fixes https://github.com/rapidsai/jupyterlab-nvdashboard/issues/199

#### Light theme

| Before | After |
| -- | -- |
| image |  image |

#### Dark theme

| Before | After |
| -- | -- |
| image | image |

#### High contrast dark theme

| Before | After |
| -- | -- |
| image | image |

### CODE REVIEW

**Review by AjayThorve — APPROVED** [review]
LGTM! Thanks alot for contributing

**Comment by krassowski** [comment]
:tada:

**Comment by AyodeAwe** [comment]
@jacobtomlinson 

`branch-24.02` for the shared-workflows is still being referenced in `pr.yaml` and `build.yaml`. These should be updated to `branch-24.10`.

Examples:
- https://github.com/rapidsai/jupyterlab-nvdashboard/blob/branch-0.12/.github/workflows/pr.yaml#L36
- https://github.com/rapidsai/jupyterlab-nvdashboard/blob/branch-0.12/.github/workflows/build.yaml#L63

**Comment by AjayThorve** [comment]
@AyodeAwe thanks! I have created a PR to fix the issue you pointed: https://github.com/rapidsai/jupyterlab-nvdashboard/pull/204

cc @jacobtomlinson

**Comment by AyodeAwe** [comment]
@AjayThorve I had thought we could simply include the needed changes in this PR but seeing that we've created a dedicated PR for it, we should get that PR merged asap, after which we should pull in the changes into this PR.

**Pull request merged**
