### PR TITLE
Bump minimum Bokeh to 2.1

### LINKED ISSUE #66: Upgrading to Bokeh 2
Current we are pinning `jupyterlab-nvdashboard` to [`bokeh` version `1`]( https://github.com/rapidsai/jupyterlab-nvdashboard/blob/1f0e39a5a0996667d1dde9226e654030020359d8/conda/recipes/jupyterlab-nvdashboard/meta.yaml#L29 ). Would be good to fix any remaining compatibility issues so `bokeh` version `2` can be used.

### PR DESCRIPTION
**Pull request by jacobtomlinson**
Some local testing seems to show that no further changes are needed.

Closes #66

### CODE REVIEW

**Comment by owenlamont** [comment]
Not sure how relevant this is but when I hacked a local copy of the nvdashboard 0.3.1 conda-forge recipe to use bokeh 2.1.1, created a new environment and launched jupyterlab 2, nvdashboard didn't render any of buttons under the GPU DASHBOARDS pane. That was the same behavior I observed with bokeh 2.1 on conda-forge when nvdashboard was missing the bokeh requirement.

no_buttons

**Comment by jacobtomlinson** [comment]
@owenlamont do you see any errors in the Jupyter Lab logs relating to this?

For my testing I created a simple environment.

```
conda create -c conda-forge -n nvdashboardtest python ipython jupyterlab nodejs
```

Then installed the extension following the developer instructions.

```
pip install -e .
jlpm install
jlpm run build
jupyter labextension install .
```

Then started `jupyter lab`.

Things seem to work fine.


image

**Comment by owenlamont** [comment]
Hi @jacobtomlinson

Yes I cloned your repo and repeated your build steps and it worked fine for me too in that environment.

For my initial conda environment that created for my local conda recipe I ran jupyter lab --debug and observed the following error that I didn't see when launching jupyterlab from your environment.

`[W 21:18:12.194 LabApp] Error loading server extension jupyter_server_proxy
    Traceback (most recent call last):
      File "/home/owen/miniconda3/envs/test_nvdash/lib/python3.8/site-packages/notebook/notebookapp.py", line 1673, in init_server_extensions
        func(self)
      File "/home/owen/miniconda3/envs/test_nvdash/lib/python3.8/site-packages/jupyter_server_proxy/__init__.py", line 27, in load_jupyter_server_extension
        server_processes += get_entrypoint_server_processes()
      File "/home/owen/miniconda3/envs/test_nvdash/lib/python3.8/site-packages/jupyter_server_proxy/config.py", line 75, in get_entrypoint_server_processes
        make_server_process(entry_point.name, entry_point.load()())
      File "/home/owen/miniconda3/envs/test_nvdash/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2460, in load
        self.require(*args, **kwargs)
      File "/home/owen/miniconda3/envs/test_nvdash/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2483, in require
        items = working_set.resolve(reqs, env, installer, extras=self.extras)
      File "/home/owen/miniconda3/envs/test_nvdash/lib/python3.8/site-packages/pkg_resources/__init__.py", line 791, in resolve
        raise VersionConflict(dist, req).with_context(dependent_req)
    pkg_resources.VersionConflict: (bokeh 2.1.1 (/home/owen/miniconda3/envs/test_nvdash/lib/python3.8/site-packages), Requirement.parse('bokeh<2'))
` 

I think I realise what I've done - I changed the bokeh<2 in the conda meta.yaml but it's still using the 0.3.1 package release with the requirements.txt bokeh<2 so conda let them install together but when launched the packages complained they aren't compatible.  My stupidity - sorry for spamming up your PR.

I'm not sure I'm allowed to review this PR (I'm still a bit of a GitHub newbie) but I will approve it if I can.

**Comment by jacobtomlinson** [comment]
No problem!

Yes you can review any PR on GitHub. If you do not have write access to the repo it will just show a grey tick instead of a green one, but it's always good to get feedback from other folks. Thanks!

**Comment by owenlamont** [comment]
Thanks for the tips, I'll keep them in mind for future.

**Pull request merged**
